### ISSUE TITLE
Update StandardAPI constructor 

### ISSUE THREAD

**Issue by sdl1** [ScottishCovidResponse/SimulationData.jl#17]
To handle this change: https://github.com/ScottishCovidResponse/data_pipeline_api/pull/64

**Comment by sdl1** [comment]
I think this requires data_pipeline_api to release `0.7.0`

**Comment by AlexRobson** [comment]
AFAICT, this is just updating `StandardAPI(...)` to `StandardAPI.from_config(...)`:

https://github.com/ScottishCovidResponse/SimulationData.jl/pull/20
